# Generated by Django 3.0.2 on 2020-01-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('quote', models.CharField(max_length=100)),
                ('img_link', models.CharField(max_length=100)),
            ],
        ),
    ]
