# Generated by Django 3.0.2 on 2020-01-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='img_link',
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.FileField(default='../static/img/customer-1.png', upload_to='static/img'),
        ),
    ]
