# Generated by Django 3.0.2 on 2020-01-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20200121_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='../static/img/customer/customer-1.png', upload_to='static/img/customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='quote',
            field=models.CharField(max_length=250),
        ),
    ]
