# Generated by Django 3.0.2 on 2020-01-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_auto_20200121_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='../static/img/customer/customer-1.png', upload_to='customer/'),
        ),
    ]
