# Generated by Django 3.0.2 on 2020-01-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
